name: Auto Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build
        run: go build -v ./...
      - name: Create new version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a v${{ github.run_number }} -m "Auto release version ${{ github.run_number }}"
          git push origin v${{ github.run_number }}
